name: .NET Core Build and SonarQube Analysis

on:
  push:
    branches: [ main ]
jobs:
  dotnet_build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test **/CITestApp.Test/CITestApp.Test.csproj --logger "trx;LogFileName=test_results.xml"

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: "**/test_results.xml"

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: dotnet publish --no-restore -c Release -o ./publish